### ISSUE TITLE
Does not work work at all and throws error

### ISSUE THREAD

**Issue by themilkman** [everyonesdesign/OpenSearchInNewTab#9]
Hi @everyonesdesign 
your plugin looks exactly like what I was searching for. Unfortunately it does not work for me at all, the behavior keeps exactly the original (also tried to restart ST). In the console I see:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/home/sweethome/.config/sublime-text-3/Installed Packages/Open Search in a New Tab.sublime-package/OpenSearchInNewTab.py", line 23, in on_activated
    if self.is_search_view(view):
  File "/home/sweethome/.config/sublime-text-3/Installed Packages/Open Search in a New Tab.sublime-package/OpenSearchInNewTab.py", line 54, in is_search_view
    name == self.get_alt_name(view)
  File "/home/sweethome/.config/sublime-text-3/Installed Packages/Open Search in a New Tab.sublime-package/OpenSearchInNewTab.py", line 29, in get_alt_name
    first_line = view.substr(sublime.Region(*first_line_coords))
TypeError: type object argument after * must be a sequence, not Region
```

I use ST 3208 under linux. Any help is very appreciated, thanks in advance!

**Comment by everyonesdesign** [comment]
Hi!

Thank you very much for reporting the issue.

I wasn't able to reproduce the issue, but saw a problem in my code that could trigger the error.

Could you, please

- Run "Package Control: Upgrade Package" menu from command palette
- Select "OpenSearchInNewTab" package

and test it again?

**Comment by themilkman** [comment]
Great, it works now and is really awesome! 
Thank you very much for your work on this plugin and this really fast reply/fix.
